<?php

/**
 * @file
 * Contains code for context_profiles.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\ContentEntityType;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function context_profiles_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.context_profiles':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>Context Profiles is a UI module for context.
What makes context profiles different from similar modules is that it does not
create own entities or add functionality, but simply provides an easy way of
using context. As a result context profiles can be en/disabled without any
affects on your application.</p>';
      $output .= '<p>Currently the main focus of context profiles lays on
placement of blocks on content entities.</p>';
      $output .= '<p>Additionally, this module allows you to organise blocks
placed by different contexts on the same page/entity view.</p>';

      return $output;
  }
}

/**
 * Implements hook_preprocess_page().
 */
function context_profiles_preprocess_page(&$variables) {
  if (\Drupal::routeMatch()->getRouteObject()->getOption('_context_profiles_entity_type_id')) {
    $variables['#attached']['library'][] = 'context_profiles/context_profiles';
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function context_profiles_entity_type_alter(array &$entity_types) {
  foreach ($entity_types as $entity_type_id => $entity_type) {
    // Only add links to content entities.
    if ($entity_type instanceof ContentEntityType) {
      $entity_type->setLinkTemplate('context-profile', "/$entity_type_id/{{$entity_type_id}}/blocks");

    }
  }
}

/**
 * Implements hook_entity_operation().
 */
function context_profiles_entity_operation(EntityInterface $entity) {
  $operations = array();
  if (\Drupal::currentUser()->hasPermission('use context profile ui')) {
    if ($entity->hasLinkTemplate('context-profile')) {
      $operations['context-profile'] = array(
        'title' => t('Blocks'),
        'weight' => 100,
        'url' => $entity->toUrl('context-profile'),
      );
    }
  }

  return $operations;
}
