context_profiles.settings:
  type: config_object
  label: 'Context Profiles settings'
  mapping:
    roles_regions:
      type: mapping
      label: 'Role based configuration for regions'
    roles_providers:
      type: mapping
      label: 'Role based configuration for providers'
